version: '3'

volumes:
  data:

services:
  mysql-bm-login:
    container_name: mysql-bm-login
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
      - MYSQL_USER=bmserver
      - MYSQL_DATABASE=bm_server
      - MYSQL_PASSWORD=abcd1234
    ports:
      - 3306:3306
    volumes:
      - data:/data/db
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]

  server-bm-login:
    image: server-bm-login
    container_name: 'server-bm-login'
    build:
      context: ../
      dockerfile: Dockerfile.local
    volumes:
      - ../:/app
    ports:
      - '3000:3000'
    depends_on:
      - mysql-bm-login
